############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Blog"
url = "#"
weight = 2
hasChildren = true

  [[main]]
  parent = "Blog"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Blog"
  name = "Categories"
  url = "categories/"
  weight = 2

[[main]]
name = "About"
url = "about/"
weight = 3

[[main]]
name = "Contact"
url = "contact/"
weight = 4



# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
